services:
  - name: lichviet-php
    type: web
    plan: free
    env: docker
    dockerfilePath: ./Dockerfile
    region: singapore

    envVars:
      - key: DB_HOST
        fromDatabase:
          name: lichviet-db
          property: host

      - key: DB_NAME
        fromDatabase:
          name: lichviet-db
          property: database

      - key: DB_USER
        fromDatabase:
          name: lichviet-db
          property: user

      - key: DB_PASS
        fromDatabase:
          name: lichviet-db
          property: password

      - key: DB_PORT
        value: "5432"

databases:
  - name: lichviet-db
    plan: free
    region: singapore
    engine: postgres
